### ISSUE TITLE
[Feature] could RMS system capture the Lightning Elf

### ISSUE THREAD

**Issue by xingxinghuo1000** [CroatianMeteorNetwork/RMS#100]
ELVES — ELVES (Emission of Light and Very Low Frequency perturbations due to Electromagnetic Pulse Sources) often appear as a dim, flattened, expanding glow.

The software UFOCaptureHD2 can capture this event. So will you Develep this new feature?

**Comment by dvida** [comment]
This software can do it: https://github.com/satmonkey/MeteorDL
