### ISSUE TITLE
Request - save .config in the CapturedFiles observation directory.

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#104]
It would be useful to have the .config file used for the observing session saved in the CapturedFiles observation directory.

**Comment by dvida** [comment]
It is already saved to ArchivedFiles - does that directory have everything you need, or do you have a specific use case where you need to use CapturedFiles?

**Comment by g7gpr** [comment]
By saving it into CapturedFiles I can have a single archive which contains all the raw data and the associated .config from an observation session. The use case for this to be able to set up a camera in one location, run a test observation, keep the reference CapturedFiles and then deploy the camera to another location.  Any quirks in the new location can then be checked against the test observation. Manually copying the .config across from ArchivedFiles is my workaround, but there is always the possibility of making an error.

**Comment by g7gpr** [comment]
Thank you. This does exactly what I need.
