### ISSUE TITLE
.config camera device

### ISSUE THREAD

**Issue by radiohound** [CroatianMeteorNetwork/RMS#13]
It might be handy to give a few options for cameras in the .config file. It took me a while to figure out I just had to put a 0 to replace this line for a CCTV analog camera. 

#analog camera
device: 0

#IP camera
#device: rtspsrc location=rtsp://192.168.42.10:554/user=admin&password=&channel=1&stream=0.sdp ! rtph264depay ! queue ! h264parse ! omxh264dec ! queue ! videoconvert ! appsink sync=1 ; device id

**Comment by dvida** [comment]
Thank you for pointing this out! 
There should definitely be a major rewrite of the readme, but for now I have added a section about this to it.
