### ISSUE TITLE
Add a limit to vignetting coefficient

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#164]
Block postprocessing when a vignetting coefficient has been provided which is unreasonable, for example

![image](https://user-images.githubusercontent.com/77130399/228049582-8676ffa3-d38d-46db-a120-06c8fd781abb.png)

**Comment by dvida** [comment]
An auto-limit is now available, it's in the dev branch for now.

**Comment by g7gpr** [comment]
Awesome. I made the exact mistake you warned us about.

**Comment by g7gpr** [comment]
Would that check actually catch all the problems? Is it possible for the vignetting coefficient to be completely wrong, but not actually cause any drop in brightness at the corners, only further in from the edge.

**Comment by g7gpr** [comment]
Deleted last comment, I see how it works now.
