### ISSUE TITLE
Adding a human friendly place name to the .config file

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#166]
Web services that provide a view of the gmn data have to maintain a mapping of station idents to place names. 

Adding an extra field into the .config file with a place name (i.e. Baldivis, Western Australia) would reduce the admin burden on the web service.

**Comment by dvida** [comment]
It's already implemented in the dev branch in preparation for the new GMN weblog. I hope to merge it soon and announce the details.
