### ISSUE TITLE
memory assignment to numpy arrays is slow when running the code under multiprocessing...

### ISSUE THREAD

**Issue by apevec** [CroatianMeteorNetwork/RMS#17]
"... The issue was apparently solved in Python 3.7, but we have not yet extensively tested it. You will need to run Raspbian Stretch to get Python 3.7 running."

^ quote from README. Is there upstream Python bug report to track?
Upgrade to Raspbian Strech is blocked by issue #16

**Comment by dvida** [comment]
https://bugs.python.org/issue30919
Apparently it was solved in Python 3.7, but I wan't able to install 3.7 under Jessie. It can be installed under Stretch through.

**Comment by apevec** [comment]
current RMS image is Buster with Python 3.7
