### ISSUE TITLE
Not issue, but question 

### ISSUE THREAD

**Issue by 3835** [CroatianMeteorNetwork/RMS#2]
What should I install to run your script? I'm explaining what I mean. Following this description - http://www.instructables.com/id/Raspberry-Pi-Meteor-Station/ - I came to the point where the script says to me:

> ERROR: Astropy requires Python 3.5 or later

I'm not a linux guy, and I do not understand the coexistence of two Python (python2.7 and python3.5 on my raspbian) at the same time. The dependencies required for the RMS operation are for versions 2.7 and 3.5 or only in 2.7, for example - python-scipy, python-matplotliblibblas-dev, python-opencv python-imaging-tk? I do not understand this. 
I will be happy for every clues:)

**Comment by dvida** [comment]
Hi,
the new versions of astropy work only on Python 3. One can install an older version that will work.
But, to make things easier, I can give you an SD card image that you can flash and everything will work out of the box. I'll PM you the details.
