### ISSUE TITLE
Station Elevation Instructions

### ISSUE THREAD

**Issue by Cybis320** [CroatianMeteorNetwork/RMS#232]
The RMS_FirstRun.sh contains the following instructions regarding the station elevation parameter:

> The elevation should be given in meters (NOT feet!) and in the mean sea level  (MSL) convention (not WGS84).
> The easiest way to measure the coordinates is in Google Earth. Make sure to pinpoint the actual location of the camera to within a precision of at least 10 meters.

I believe the required measurement is the Height Above Ellipsoid (HAE), right?

Google Earth, however, provides the Height Above Geoid (HAG). Raw GPS altitude is HAE but GPS's are not super precise on vertical axis. iPhone's 'GPS' elevation data is not raw GPS data but is based on HAG. I'm unsure about the situation with Android devices.

Should the instructions be changed to reflect that if Google Earth or smartphone's GPS are used to determined elevation, it should be adjusted from HAG to HAE?

**Comment by dvida** [comment]
The code will convert vaules from EGM96 model values into WGS84. My design, EGM96 model defines the mean sea level.

There are slight differences between HAG and MSL, so the correct answer is MSL, although HAG is close enough. The value required by RMS is definitely not HAE/WGS84.
