### ISSUE TITLE
Allow RMS to pull updated mask from server

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#238]
Similar to arrangement for platepars, allow RMS to pull an updated mask from gmn.uwo.ca

**Comment by dvida** [comment]
Yes, that would absolutely be necessary and something I had in mind for a long time!

**Comment by g7gpr** [comment]
What would you prefer?

Make downloadPlatepar general purpose by adding an optional argument? Or just create a new module?

I'd prefer to create a new module, although we will have duplicated code, it prevents breaking a working function.

**Comment by g7gpr** [comment]
Pull request 239 in draft

**Comment by g7gpr** [comment]
Ready for testing.
