### ISSUE TITLE
'bad marshal data' Python error

### ISSUE THREAD

**Issue by sammmelg** [CroatianMeteorNetwork/RMS#322]
Hello,
An error cropped up on one of my stations (USL017) and Denis advised me to open an issue describing the error and how I solved it.

When RMS_StartCapture initiated, several lines would run before the Python error 'ValueError: bad marshal data (unknown type code' would pop up and cause the script to crash. I found out through a google search that this error can be cause by corrupted .pyc files. To solve the error, I went thru the traceback and deleted .pyc files out of the '__pycache__' folder for the packages that showed up on the traceback. I also restarted RMS_StartCapture.sh after each one, to see if the correct .pyc file had been deleted. Finally, once all of the corrupted files had been deleted, StartCapture came up with no issues and has been running successfully for about a week now.

Attached is a screenshot of the error that was showing up.

Sam Hemmelgarn

<img width="1511" alt="bmd_python_error" src="https://github.com/user-attachments/assets/be486980-045c-4929-bcd1-25cd69d998d4">

**Comment by dvida** [comment]
Agreed, would you mind addressing this? Perhaps there already is a mechanism in setup.py that we haven't implemented, it would only make sense.

**Comment by markmac99** [comment]
You could add pyclean to the requirements, then run 
```
pyclean -v --debris all 
```
This would be a pretty safe way to clear out any cached and other temporary files.
