### ISSUE TITLE
Line 347 in .config starts with a space in prerelease

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#354]
https://github.com/CroatianMeteorNetwork/RMS/blob/6c3643bc57d5a73a2de255d0801ddabd67d5dba7/.config#L347

Also 

https://github.com/CroatianMeteorNetwork/RMS/blob/6c3643bc57d5a73a2de255d0801ddabd67d5dba7/.config#L118

various lines are using bash style comments

**Comment by Cybis320** [comment]
Thank you. I'll fix that.

**Comment by Cybis320** [comment]
Merged and closed.
