### ISSUE TITLE
Options for mask and platepar are missing from .config in prerelease

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#355]
Is this an intended change to prevent alteration?

**Comment by Cybis320** [comment]
Yes. We don't want to expose the options to change mask and platepar names in config as per Denis request.

There were added to the omit list in AuditConfig:
```python
OMIT_FROM_CONFIG = {'lat',
                    'lon',
                    'location',
                    'altitude',
                    'event_monitor_db_name',
                    'force_v4l2',
                    'mask',
                    'platepar_name'
                    }
```
Is there a use case to keep them in config?

**Comment by g7gpr** [comment]
Not to my knowledge. Thank you.
