### ISSUE TITLE
Flux doesn't use mask?

### ISSUE THREAD

**Issue by Cybis320** [CroatianMeteorNetwork/RMS#388]
Maybe I’m confused, but it seems Flux doesn’t use the mask because it’s looking for it in the Capture folder. However, there is no mask there. The mask is located in the same directory as the .config file and is copied to the Archive folder. Am I seeing this right? It doesn't help that Flux doesn't log.

**Comment by dvida** [comment]
Addressed in #395

**Comment by Cybis320** [comment]
Merged into Master. Closing.
