### ISSUE TITLE
Reprocesing fails if invalid pickle found

### ISSUE THREAD

**Issue by satmonkey** [CroatianMeteorNetwork/RMS#403]
During reprocessing, if there is invalid pickle found ("Invalid load key"), the reprocessing stops.
It either should try to create the pickle again, or continue processing next pickle.
![image](https://github.com/user-attachments/assets/1bc11f0f-2b5c-4795-8e4f-28d8f22f474e)

**Comment by g7gpr** [comment]
@satmonkey, would you be able to confirm that this is resolved?

**Comment by satmonkey** [comment]
@g7gpr , no occurence here since the fix applied, therefore resolved. Thank you.
