### ISSUE TITLE
Unhelpful print call in ObservationSummary

### ISSUE THREAD

**Issue by g7gpr** [CroatianMeteorNetwork/RMS#430]
https://github.com/CroatianMeteorNetwork/RMS/blob/4ab05b037ee5ada27cd7df1797e812b7d47b3a53/RMS/Formats/ObservationSummary.py#L243

Line above prints information to console, which is neither neatly formatted nor helpful. Propose to comment this line out.

**Comment by jacklinna** [comment]
nice
