### ISSUE TITLE
Distance formula in testPoints

### ISSUE THREAD

**Issue by IlyinSlava** [CroatianMeteorNetwork/RMS#486]
I may be missing something, but this distance formula doesn't look correct at first glance (2 `z` coordinates and no `x`):

https://github.com/CroatianMeteorNetwork/RMS/blob/f8cb6350b53e8b6d1e14dedeab9b4c6a8b9bf7a9/RMS/Routines/Grouping3Dcy.pyx#L552

Is it supposed to be like that?

**Comment by Cybis320** [comment]
Good catch!

**Comment by dvida** [comment]
It's a 7-year-old bug, thanks for catching it! I fixed it now.
