### ISSUE TITLE
Variables mix-up in ConfigReader

### ISSUE THREAD

**Issue by devcenary** [CroatianMeteorNetwork/RMS#487]
`frame_dirs_to_keep` overrides the value of `bz2_files_to_keep`

https://github.com/CroatianMeteorNetwork/RMS/blob/e87c8080af987b2b0ed3dcca5ee616aa54f6fcc6/RMS/ConfigReader.py#L968

**Comment by Cybis320** [comment]
Good catch! Thank you.

**Comment by dvida** [comment]
Fixed by #490
