### ISSUE TITLE
cml_args.resume is called inside runCapture() without being declared global or passed in

### ISSUE THREAD

**Issue by Cybis320** [CroatianMeteorNetwork/RMS#489]
I'm probably missing something and I don't understand why it's not throwing an error but  I don't think `cml_args.resume = False` will work as intended here because cml_args is not being passed in, right?:
https://github.com/CroatianMeteorNetwork/RMS/blob/e87c8080af987b2b0ed3dcca5ee616aa54f6fcc6/RMS/StartCapture.py#L160-L221

**Comment by dvida** [comment]
Fixed in prerelease
