### ISSUE TITLE
[OUTPUT format] How do I get colorful outputs?

### ISSUE THREAD

**Issue by xingxinghuo1000** [CroatianMeteorNetwork/RMS#99]
When there is a thunder storm whether. I wish RMS system could capture the red elf (red jet / blue jet) in the sky.
So, color images are Mus. Or else only the grey elf is captured

**Comment by dvida** [comment]
Colours are not useful for meteor astronomy, thus RMS only supports B/W. Also, including colours would increase the data size 3x, which is not feasible on the Pis.
